In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving movies_stats.csv to movies_stats.csv

In [ ]:
df = pd.read_csv('movies_stats.csv')
df.head(10)

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama
5,1,1263,2.0,1260759151,"Deer Hunter, The (1978)",Drama|War
6,1,1287,2.0,1260759187,Ben-Hur (1959),Action|Adventure|Drama
7,1,1293,2.0,1260759148,Gandhi (1982),Drama
8,1,1339,3.5,1260759125,Dracula (Bram Stoker's Dracula) (1992),Fantasy|Horror|Romance|Thriller
9,1,1343,2.0,1260759131,Cape Fear (1991),Thriller

In [ ]:
def production_year(row):
    years = range(1950, 2011)

    for year in years:
        if str(year) in str(row):
            return year

    return '1900'

df['year'] = df['title'].apply(production_year)
df.head(10)

,userId,movieId,rating,timestamp,title,genres,year
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama,1995
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical,1900
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,1996
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,1981
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,1989
5,1,1263,2.0,1260759151,"Deer Hunter, The (1978)",Drama|War,1978
6,1,1287,2.0,1260759187,Ben-Hur (1959),Action|Adventure|Drama,1959
7,1,1293,2.0,1260759148,Gandhi (1982),Drama,1982
8,1,1339,3.5,1260759125,Dracula (Bram Stoker's Dracula) (1992),Fantasy|Horror|Romance|Thriller,1992
9,1,1343,2.0,1260759131,Cape Fear (1991),Thriller,1991

In [ ]:
df['year'] = pd.to_numeric(df['year'], errors='coerce')

In [ ]:
print(df['year'].dtype)

int64

In [ ]:
df['year'].unique()

array([1995, 1900, 1996, 1981, 1989, 1978, 1959, 1982, 1992, 1991, 1979,
       1971, 1980, 1988, 1998, 1986, 1974, 1994, 1993, 1990, 1970, 1987,
       1983, 1997, 1999, 1984, 2000, 2002, 2003, 2004, 2006, 2008, 2009,
       1977, 1972, 1958, 1950, 1964, 1951, 1975, 1960, 1985, 1962, 1976,
       1967, 1955, 1961, 1953, 1973, 1965, 2001, 2005, 1957, 1954, 1968,
       1966, 2007, 2010, 1952, 1963, 1969, 1956])

In [ ]:
df.groupby('year').agg({'rating': 'mean'}).sort_values(by='rating', ascending=False)

        rating
year
1957  4.014241
1972  4.011136
1952  4.000000
1954  3.994220
1951  3.983539
...        ...
2005  3.448434
2003  3.444777
1996  3.426600
1997  3.415764
2000  3.356104

[62 rows x 1 columns]